// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function LoginLayout({ children }) {
  return <html lang="en">{children}</html>;
}
/**
 *   <html lang="en">
      <Provider store={store}>
        <body className={inter.className}>
          <HomePageHeader></HomePageHeader>
          {children}
        </body>
      </Provider>
    </html>
 */
