"use client";

import { store } from "@/app/redux/store";
import { Box } from "@mui/material";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import { whiteColor_v_2 } from "../../../color";
import Footer from "../components/Footer/Footer";
import CustomerHeader from "../components/HomePageHeader/CustomerHeader";
import InfoBar from "../components/InfoBar/InfoBar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function productCart({ children }) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body
          className={inter.className}
          style={{ backgroundColor: whiteColor_v_2 }}
        >
          <Box
            component="main"
            sx={{
              backgroundColor: whiteColor_v_2,
              padding: { xs: "0", lg: "5px 50px" }, // No padding on small screens, padding on large screens
              backgroundColor: "black",
            }}
          >
            <InfoBar />
          </Box>

          <Box
            component="main"
            sx={{
              backgroundColor: whiteColor_v_2,
              padding: { xs: "0", lg: "0 50px" }, // No padding on small screens, padding on large screens
              backgroundColor: "white",
              position: "sticky", // Makes the header sticky
              top: 0, // Sticks to the top
              zIndex: 1000, // Ensures the header stays on top
              boxShadow: "0 4px 10px rgba(0, 0, 0, 0.1)", // Adds shadow for 3D effect
              top: 0, // Sticks to the top
              zIndex: 1000, // Ensures the header stays on top
              boxShadow: "0 4px 10px rgba(0, 0, 0, 0.1)", // Adds shadow for 3D effect
              top: 0, // Sticks to the top
              zIndex: 1000, // Ensures the header stays on top
              boxShadow: "0 4px 10px rgba(0, 0, 0, 0.1)", // Adds shadow for 3D effect
              top: 0, // Sticks to the top
              zIndex: 1000, // Ensures the header stays on top
            }}
          >
            <CustomerHeader></CustomerHeader>
          </Box>

          {children}
          <Footer></Footer>
        </body>
      </Provider>
    </html>
  );
}

// <HomePageHeader></HomePageHeader>
